---
# author: wei.gao

- name: debug | 打印 变量
  debug: msg="app = {{ app }}, lang = {{ lang }}, html_path = {{ html_path }}"

- name: check | 检查 openresty {{ nginx_port }} 是否开启
  shell: ps -ef | grep nginx | grep -v grep | awk '{print $2}'
  register: var_pid

- name: debug | 打印 pid
  debug: msg="{{ var_pid }}"

- name: stop |  强制 停止openresty
  shell: kill -9 {{ item }}
  with_items: "{{ var_pid.stdout_lines }}"
  ignore_errors: true
  when: var_pid.stdout != ''

- name: stop |  等待端口关闭
  wait_for: port={{ nginx_port }} state=stopped delay=3

- name: stop |  清理旧文件
  shell: "rm -rf {{ nginx_path }}{{ item }}/*"
  with_items:
    - html
    - logs

- name: deploy | 上传 dist
  copy: src={{ html_path }} dest={{ nginx_path }}html/

- name: deploy | 启动服务
  shell: nohup {{ nginx_path }}sbin/nginx &
  ignore_errors: true