---
# author: wei.gao

- name: debug | debug params
  debug: msg="app = {{ app }}, lang = {{ lang }}, html_path = {{ html_path }}"

- name: stop | stop nginx -s stop
  shell: "{{ nginx_path }}sbin/nginx -s stop"
  ignore_errors: true

- name: stop |  wait {{ nginx_port }} stop
  wait_for: port={{ nginx_port }} state=stopped timeout=3
  register: rs
  ignore_errors: true

- block:
    - name: debug | debug rs
      debug: msg="{{ rs }}"
      when: rs.failed == false

    - name: check | nginx pid
      shell: ps -ef | grep nginx | grep -v grep | awk '{print $2}'
      register: var_pid

    - name: stop |  kill -9 openresty
      shell: kill -9 {{ item }}
      with_items: "{{ var_pid.stdout_lines }}"
      when: var_pid.stdout != ''

    - name: stop |  next wait {{ nginx_port }} stop
      wait_for: port={{ nginx_port }} state=stopped timeout=3
  when: rs.failed == true

- name: stop |  rm old files
  shell: "rm -rf {{ nginx_path }}{{ item }}/*"
  with_items:
    - html
    - logs

- name: deploy | upload dist
  copy: src={{ html_path }} dest={{ nginx_path }}html/

- name: deploy | start nginx
  shell: "nohup {{ nginx_path }}sbin/nginx &"
  ignore_errors: true