---
# author: wei.gao

- name: debug |  print params
  debug: msg="app = {{ app }}, lang = {{ lang }}, war_path = {{ war_path }}"

- name: backup | create dir {{ tomcat_path }}backup
  file: path={{ tomcat_path }}backup state=directory

- name: backup | cp war
  shell: cp -r {{ tomcat_path }}webapps/{{ app }}.war  {{ tomcat_path }}backup/{{ app }}-`date '+%F'`.war
  ignore_errors: true

- name: stop |  stop tomcat
  shell: "{{ tomcat_path }}bin/catalina.sh stop -force"

- name: stop |  wait {{ tomcat_port }} stop
  wait_for: port={{ tomcat_port }} state=stopped timeout=3
  register: rs
  ignore_errors: true

- block:
    - name: debug | print rs
      debug: msg="{{ rs }}"

    - name: check | find pid
      shell: ps -ef | grep tomcat | grep {{ tomcat_path }} | grep -v grep | awk '{print $2}'
      register: var_pid

    - name: debug | print pid
      debug: msg="{{ var_pid }}"

    - name: stop |  kill -9 pid
      shell: kill -9 {{ var_pid.stdout }}
      when: var_pid.stdout != ''

    - name: stop |  next wait {{ tomcat_port }} stop
      wait_for: port={{ tomcat_port }} state=stopped timeout=3
  when: rs.failed == true

- name: stop |  rm old files
  shell: "rm -rf {{ tomcat_path }}{{ item }}/*"
  with_items:
    - webapps
    - work
    - logs
    - temp

- name: deploy | update {{ war_path }}
  copy: src={{ war_path }} dest={{ tomcat_path }}webapps/

- name: deploy | start tomcat
  shell: chdir={{ tomcat_path }}bin nohup ./catalina.sh start &
  ignore_errors: true